### ISSUE TITLE
Bootstrap script does not create HTTPs ELB when ACM cert is not provided

### ISSUE THREAD

**Issue by chitsaou** [degica/barcelona#377]
Hi there, (me again)

I am trying out Barcelona by following getting_started.md .

I found that if I did not specify an ACM Certificate during bootstrap, Barcelona won't create an ELB listener for HTTPS, and:

* HTTPS could not be connected
  * It is not possible to do `bcn login https://blah-blah` because 443 is not enabled

I understand that it's not possible to create a HTTPS listener on ELB without a certificate. However, I think it's worth to add more description to the bootstrap message:

```
Create a new certificate on Amazon Certificate Manager in the region you chose and provide its ARN.
This is optional but we highly recommend to setup ACM certificate.
```

To something that asks the user to enable HTTPS listener itself, after the provisioning is finished.

Thanks!

**Comment by k2nr** [comment]
Hi, yes you are right that if you don't specify ACM ARN, HTTPS is not available. The bootstrap creates an endpoint whose name is `barcelona` so you can update the endpoint's certificate with the below client command.

```
$ bcn endpoint update --certificate-arn=<ACM ARN> barcelona
```

Note that this `endpoint update` operation is done through plain HTTP request if you didn't set ACM ARN to the bootstrap script. So giving ACM ARN to the bootstrap script is the only safe way (that's why it is recommended)

I agree that this should be explained in the bootstrap message, I will add it later.

Thank you for opening this issue!
